import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Header from "@/components/Header";
import Card_qualification from "@/components/Card_qualification";
import Bnt_SimularOrcamento from "@/components/Bnt_SimularOrcamento";
import Sobre from "@/components/Sobre"
import Servicos from "@/components/Servicos";
import Status_loja from "@/components/Status_loja";
import Card_vendas from "@/components/Cards_vendas"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container_main}>
      
      <Header />
        
      <section className={styles.container_title}>
          <div className={styles.title_conteudo} >
            <h2> Assistêcia técnica Especializada <br /> </h2>
            <h1> Tá precisando de uma força <br /> com seu dispositivo ? </h1>
            <p> Caiu, Quebrou, parou de funcionar ?! traga Seu equipamento <br /> para quem realmente entende do Assunto.</p>
            <Bnt_SimularOrcamento />
          </div>
          <img src="/Conserto-de-celular.png" alt="Logo" className={styles.imagem_reparo}/>
          <Card_qualification />
      </section>
      
      <Sobre />

      <Servicos />
      <Status_loja/>
      <Card_vendas />
      </main>
      
        
      



    </>
  );
}
